# Generated by Django 3.2.9 on 2021-11-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='details',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='titre',
        ),
    ]
